namespace HCSampleApp.Droid.Temprueture
{
    public enum Enums
    {
        MESSAGE_DEVICE_FOUND = 10000,
        MESSAGE_TEMPERATURE_UPDATE = 10001,
        MESSAGE_DEVIE_LOST = 10002,
        MESSAGE_TEMPERATURE_MISSED = 10003,
        MESSAGE_PHONE_BLUETOOTH_OFF = 10004,
        MESSAGE_PHONE_LOCATION_OFF = 10005,
        MESSAGE_TEMPERATURE_ABNORAML = 10006,
        MESSAGE_TEMPERATURE_STABLE = 10007,
        MESSAGE_TEMPERATURE_NOT_STABLE = 10008,
        MESSAGE_DEVICE_LONG_TIME_MISS = 10009,
        MESSAGE_CHARGER_INFO_UPDATED = 10010,
    }
}